

---FIND THE PH NUMBER WHICH HAS MORE OUT THAN IN
-------------SOLUTION
SELECT CALL_NUMBER
    FROM call_details 
   -- WHERE CALL_NUMBER IN (SELECT CALL_NUMBER  FROM call_details WHERE CALL_TYPE='OUT' INTERSECT SELECT CALL_NUMBER  FROM call_details WHERE CALL_TYPE='INC')
    GROUP BY CALL_NUMBER 
    HAVING SUM (CASE WHEN CALL_TYPE='OUT' THEN CALL_DURATION END) >0
    AND SUM (CASE WHEN CALL_TYPE='INC' THEN CALL_DURATION END)>0 AND 
    SUM (CASE WHEN CALL_TYPE='OUT' THEN CALL_DURATION END) > SUM (CASE WHEN CALL_TYPE='INC' THEN CALL_DURATION END)
    ORDER BY CALL_NUMBER;
